### ISSUE TITLE
php 8.0 errors: vendor/openpsa/quickform/lib/HTML/QuickForm/element.php:62 Cannot call constructor

### ISSUE THREAD

**Issue by schulzrinne** [openpsa/quickform#25]
vendor/openpsa/quickform/lib/HTML/QuickForm/element.php:62 Cannot call constructor

Appears wherever parent::__construct($attributes); is called. Not clear what the fix would be.

**Comment by flack** [comment]
Do you have any code to reproduce this issue? Just looking at the code it seems like it should work and I seem to remember that I ran quickform (indirectly through some testsuite) on PHP8 a couple of times, and it never complained about something like that

**Comment by schulzrinne** [comment]
Error:

/mnt/edas/html/vendor/openpsa/quickform/lib/HTML/QuickForm.php:246 Cannot
call constructor

Error at line 246 in
/mnt/edas/html/vendor/openpsa/quickform/lib/HTML/QuickForm.php
Code:

$f = new HTML_QuickForm('form', 'post', '', '_self', null, true);

$f->addElement('submit', 'action', 'Update');


if ($f->validate()) {

  $f->process('form');

} else {

  $f->display();

}

**Comment by retry-the-user** [comment]
Out of curiosity, what happens if you just try to instantiate without any parameters like:

$qf = new HTML_QuickForm();

**Comment by flack** [comment]
@schulzrinne I tried your sample code on PHP 8.0.6 and on my machine it worked without errors. lib/HTML/QuickForm.php line 246 calls the parent constructor from lib/HTML/Common.php line 66. I'm not sure what could go wrong with that. Did you modify the source code in any way? Or could it be that you somehow have a separate copy of HTML_Common that's missing the constructor?

**Comment by retry-the-user** [comment]
Perhaps the issue is with the way you're trying to load Common.php ? Are you using a require/include or autoloading?

**Comment by schulzrinne** [comment]
Yes - a version of that. I'm using the HTML_Table PEAR library, and it includes the old Common.php. I have not found a more modern compatible version of HTML_Table. A kludge that seems to work: I edited the old Common.php to include both the old-style class constructor and the __construct() version.

**Comment by flack** [comment]
yes, that explains it: PHP8 does not recognize old PHP4-style constructors any more, so that's why it stoppped working. I guess as an alternative you could try to fiddle with your autoloader to make sure `HTML_Common` is always loaded from this repo, but manually patching seems fine, too (and I suspect you'll probably have to patch more places as times goes by).
